apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  pg-db: {{ .Values.app.environment.POSTGRES_DB | b64enc | quote }}
  pg-user: {{ .Values.app.environment.POSTGRES_USER | b64enc | quote }}
  pg-password: {{ .Values.app.environment.POSTGRES_PASSWORD | b64enc | quote }}